server:
  port: 18950

spring:
  datasource:
  url: jdbc:mysql://101.43.242.216:3306/brbdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  username: root
  password: "012345"
  driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  type-aliases-package: com.save.brbserver.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: kjFBjnlndnlanlf

#logging:
#  file:
#    name:  E:/BRB/spring-test.log  # 日志文件绝对路径及名称
#  level:
#    root: info #日志级别 root表示所有包，也可以单独配置具体包 fatal>error>warn>info>debug>trace>off

#swagger:
#  enabled: true